services:
  oncater_backend:
    image: ghcr.io/Branak/esturio/backend:production
    mem_limit: 1G
    mem_reservation: 512M
    ports:
      - "3001:3001"
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3001
