services:
  esturio_backend:
    image: ghcr.io/elvisuriel/esturio-back:production
    mem_limit: 1G
    mem_reservation: 512M
    ports:
      - "3001:3001"
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3001
